services:

  mission-engine:
    build: .
    container_name: mission-engine
    env_file:
      - .env
    restart: always
    depends_on:
      - graph-db

  graph-db:
    image: neo4j:5
    container_name: graph-db
    restart: always
    environment:
      NEO4J_AUTH: neo4j/password123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs: